### ISSUE TITLE
Full compile instructions + built binaries for download so you don't have to

### ISSUE THREAD

**Issue by deividAlfa** [konsgn/BlueMagic#2]
**Compiled binaries**

[bluemagic.zip](https://github.com/user-attachments/files/18229117/bluemagic.zip): Needs bootloader installed.
[bluemagic_no_bootloader.zip](https://github.com/user-attachments/files/18229457/bluemagic_no_bootloader.zip): No bootloader, simply flash with stlink/jlink/etc and run.
<br>
**Steps to compile the firmware**

Open a console / shell in your Home folder.

Install basic dependencies:

    sudo apt update
    sudo apt install git gcc-arm-none-eabi -y

Clone the repo:

    git clone --recursive https://github.com/konsgn/BlueMagic

Compile:

    cd BlueMagic
    make -C libopencm3 TARGETS=stm32/f1 all
    make all
<br>
If you don't want or have bootloader, edit Makefile and change this line:

    LDFLAGS = $(LDFLAGS_BOOT) -Wl,-Ttext=0x08002000

To:

    LDFLAGS = $(LDFLAGS_BOOT) -Wl,-Ttext=0x08000000

That way it can be directly flashed with a ST-Link or other programmers and work right away.

Cheers

**Comment by konsgn** [comment]
Updated! Thanks!

**Comment by deividAlfa** [comment]
Hey, I had to revisit this, made better instructions + compiled binary. 
It would be a good idea to put the binary in Releases so people don't have to compile it everytime!
Regards
